    // let result = do_something_fail(12);
    // match result{
    //     Ok(v)=>println!("found {}",v),
    //     Err(e)=>{
    //         return Err(String::from("something went wrong in main"))
    //     }
    // }